export const GET_BALANCE_START = 'GET_BALANCE_START';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';

export const UPDATE_BALANCE = 'UPDATE_BALANCE';

export const GET_ACCOUNT_NUMBER_START = 'GET_ACCOUNT_NUMBER_START';
export const GET_ACCOUNT_NUMBER_SUCCESS = 'GET_ACCOUNT_NUMBER_SUCCESS';
export const GET_ACCOUNT_NUMBER_FAILURE = 'GET_ACCOUNT_NUMBER_FAILURE';

export const GET_BVN_START = 'GET_BVN_START';
export const GET_BVN_SUCCESS = 'GET_BVN_SUCCESS';
export const GET_BVN_FAILURE = 'GET_BVN_FAILURE';

export const ENQUIRE_ACCOUNT_START = 'ENQUIRE_ACCOUNT_START';
export const ENQUIRE_ACCOUNT_SUCCESS = 'ENQUIRE_ACCOUNT_SUCCESS';
export const ENQUIRE_ACCOUNT_FAILURE = 'ENQUIRE_ACCOUNT_FAILURE';

export const SET_ACTIVE_ACCOUNT = 'SET_ACTIVE_ACCOUNT';
