export const RETRIEVE_BENEFICIARIES_START = 'RETRIEVE_BENEFICIARIES_START';
export const RETRIEVE_BENEFICIARIES_SUCCESS = 'RETRIEVE_BENEFICIARIES_SUCCESS';
export const RETRIEVE_BENEFICIARIES_FAILURE = 'RETRIEVE_BENEFICIARIES_FAILURE';

export const DELETE_BENEFICIARIES_START = 'DELETE_BENEFICIARIES_START';
export const DELETE_BENEFICIARIES_SUCCESS = 'DELETE_BENEFICIARIES_SUCCESS';
export const DELETE_BENEFICIARIES_FAILURE = 'DELETE_BENEFICIARIES_FAILURE';

export const ADD_BENEFICIARIES_START = 'ADD_BENEFICIARIES_START';
export const ADD_BENEFICIARIES_SUCCESS = 'ADD_BENEFICIARIES_SUCCESS';
export const ADD_BENEFICIARIES_FAILURE = 'ADD_BENEFICIARIES_FAILURE';
