export const RETRIEVE_BILLS_START = "RETRIEVE_BILLS_START";
export const RETRIEVE_BILLS_SUCCESS = "RETRIEVE_BILLS_SUCCESS";
export const RETRIEVE_BILLS_FAILURE = "RETRIEVE_BILLS_FAILURE";

export const RETRIEVE_CATEGORY_BILLS_START = "RETRIEVE_CATEGORY_BILLS_START";
export const RETRIEVE_CATEGORY_BILLS_SUCCESS = "RETRIEVE_CATEGORY_BILLS_SUCCESS";
export const RETRIEVE_CATEGORY_BILLS_FAILURE = "RETRIEVE_BILLERS_PRODUCT_";

export const RETRIEVE_BILLERS_PRODUCT_START = "RETRIEVE_BILLERS_PRODUCT_START";
export const RETRIEVE_BILLERS_PRODUCT_SUCCESS = "RETRIEVE_BILLERS_PRODUCT_SUCCESS";
export const RETRIEVE_BILLERS_PRODUCT_FAILURE = "RETRIEVE_BILLERS_PRODUCT_FAILURE";

export const PAY_BILL_SUCCESS = "PAY_BILL_SUCCESS";
export const PAY_BILL_START = "PAY_BILL_START";
export const PAY_BILL_FAILURE = "PAY_BILL_FAILURE";

export const RETRIEVE_SCHEDULED_BILLS_START = "RETRIEVE_SCHEDULED_BILLS_START";
export const RETRIEVE_SCHEDULED_BILLS_SUCCESS = "RETRIEVE_SCHEDULED_BILLS_SUCCESS";
export const RETRIEVE_SCHEDULED_BILLS_FAILURE = "RETRIEVE_SCHEDULED_BILLS_FAILURE";

export const CANCEL_SCHEDULED_BILLS_START = "CANCEL_SCHEDULED_BILLS_START";
export const CANCEL_SCHEDULED_BILLS_SUCCESS = "CANCEL_SCHEDULED_BILLS_SUCCESS";
export const CANCEL_SCHEDULED_BILLS_FAILURE = "CANCEL_SCHEDULED_BILLS_FAILURE";

export const RETRIEVE_RECURRING_BILLS_START = "RETRIEVE_RECURRING_BILLS_START";
export const RETRIEVE_RECURRING_BILLS_SUCCESS = "RETRIEVE_RECURRING_BILLS_SUCCESS";
export const RETRIEVE_RECURRING_BILLS_FAILURE = "RETRIEVE_RECURRING_BILLS_FAILURE";

export const CANCEL_RECURRING_BILLS_START = "CANCEL_RECURRING_BILLS_START";
export const CANCEL_RECURRING_BILLS_SUCCESS = "CANCEL_RECURRING_BILLS_SUCCESS";
export const CANCEL_RECURRING_BILLS_FAILURE = "CANCEL_RECURRING_BILLS_FAILURE";

export const CREATE_SCHEDULED_BILL_START = "CREATE_SCHEDULED_BILL_START";
export const CREATE_SCHEDULED_BILL_SUCCESS = "CREATE_SCHEDULED_BILL_SUCCESS";
export const CREATE_SCHEDULED_BILL_FAILURE = "CREATE_SCHEDULED_BILL_FAILURE";
