export const TRANSACTION_START = 'TRANSACTION_START';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';
export const TRANSACTION_FAILURE = 'TRANSACTION_FAILURE';

export const RETRIEVE_BANK_CODES_START = 'RETRIEVE_BANK_CODES_START';
export const RETRIEVE_BANK_CODES_SUCCESS = 'RETRIEVE_BANK_CODES_SUCCESS';
export const RETRIEVE_BANK_CODES_FAILURE = 'RETRIEVE_BANK_CODES_FAILURE';

export const RETRIEVE_TRANSACTIONS_START = 'RETRIEVE_TRANSACTIONS_START';
export const RETRIEVE_TRANSACTIONS_SUCCESS = 'RETRIEVE_TRANSACTIONS_SUCCESS';
export const RETRIEVE_TRANSACTIONS_FAILURE = 'RETRIEVE_TRANSACTIONS_FAILURE';

export const RETRIEVE_TRANSACTION_ANALYTICS_START = 'RETRIEVE_TRANSACTION_ANALYTICS_START';
export const RETRIEVE_TRANSACTION_ANALYTICS_SUCCESS = 'RETRIEVE_TRANSACTION_ANALYTICS_SUCCESS';
export const RETRIEVE_TRANSACTION_ANALYTICS_FAILURE = 'RETRIEVE_TRANSACTION_ANALYTICS_FAILURE';

export const RETRIEVE_TRANSACTION_CHART_START = 'RETRIEVE_TRANSACTION_CHART_START';
export const RETRIEVE_TRANSACTION_CHART_SUCCESS = 'RETRIEVE_TRANSACTION_CHART_SUCCESS';
export const RETRIEVE_TRANSACTION_CHART_FAILURE = 'RETRIEVE_TRANSACTION_CHART_FAILURE';

export const RETRIEVE_BANK_STATEMENT_START = 'RETRIEVE_BANK_STATEMENT_START';
export const RETRIEVE_BANK_STATEMENT_SUCCESS = 'RETRIEVE_BANK_STATEMENT_SUCCESS';
export const RETRIEVE_BANK_STATEMENT_FAILURE = 'RETRIEVE_BANK_STATEMENT_FAILURE';

export const ADD_BASE_TRANSACTION = 'ADD_BASE_TRANSACTION';
export const SAVE_TRANSACTION_CONSTANTS = 'SAVE_TRANSACTION_CONSTANTS';

export const ADD_MONEY_BY_CARD_START = 'ADD_MONEY_BY_CARD_START';
export const ADD_MONEY_BY_CARD_SUCCESS = 'ADD_MONEY_BY_CARD_SUCCESS';
export const ADD_MONEY_BY_CARD_FAILURE =  'ADD_MONEY_BY_CARD_FAILURE';
