export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';

export const UPDATE_USER_DETAILS_START = 'UPDATE_USER_DETAILS_START';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';
